<template>
  <div>
    <div class="h-screen flex flex-col gap-4 items-center justify-center">
      <!-- Card 1 -->
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
        :rank="1"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
        :rank="2"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
        :rank="3"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
      <leaderboard-card
        userAvatar="https://picsum.photos/seed/2/200/200"
        userName="zal1000"
        score="20"
      />
    </div>
  </div>
</template>
