apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reggeltbot
  managedFields:
    - apiVersion: apps/v1
      manager: GoogleCloudConsole
      operation: Update
      time: '2021-05-17T20:10:56Z'
  name: reggeltbot
  namespace: default
spec:
  progressDeadlineSeconds: 1000
  replicas: 1
  selector:
    matchLabels:
      app: reggeltbot
  strategy:
    rollingUpdate:
      maxSurge: '1'
      maxUnavailable: '0'
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: reggeltbot
    spec:
      containers:
        - env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                configMapKeyRef:
                  key: GOOGLE_APPLICATION_CREDENTIALS
                  name: reggeltbot-config-pdn4
            - name: GOOGLEAPIKEY
              valueFrom:
                configMapKeyRef:
                  key: GOOGLEAPIKEY
                  name: reggeltbot-config-pdn4
            - name: STATUSPAGE_KEY
              valueFrom:
                configMapKeyRef:
                  key: STATUSPAGE_KEY
                  name: reggeltbot-config-pdn4
          image: gcr.io/zal1000/github.com/zal1000/reggeltbot
          imagePullPolicy: IfNotPresent
          name: reggeltbot-1
          resources:
            limits:
              cpu: '0.5'
              memory: '1Gi'
            requests:
              cpu: '0.05'
              memory: '200MiB'
      serviceAccountName: reggeltbot-prod
      
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: reggeltbot
  name: reggeltbot-hpa-gvwn
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: reggeltbot
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reggeltbot
  name: reggeltbot-service
  namespace: default
spec:
  clusterIP: 10.8.12.173
  clusterIPs:
    - 10.8.12.173
  ports:
    - port: 3000
      protocol: TCP
      targetPort: '3000'
  selector:
    app: reggeltbot
  sessionAffinity: None
  type: ClusterIP
