name: Build and deploy to Cloud Run (refactor)

on:
  push:
    branches:
      - refactor
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup GCP Service Account
      uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build container image
      run: |
        cd web
        docker build --tag gcr.io/zal1000/reggeltbot/refactor/web:$GITHUB_SHA .
  
    - name: Push container image to gcr.io
      run: |
        docker push gcr.io/zal1000/reggeltbot/refactor/web:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy reggeltbot-web-beta \
        --region europe-west1 \
        --image gcr.io/zal1000/reggeltbot/refactor/web:$GITHUB_SHA \
        --platform managed \
        --allow-unauthenticated \
        --project zal1000